#!/usr/bin/env bash
# Show every agent window and every held lock.
# Usage: agent-status.sh [--write]   --write also writes .agent/state/project-state.yaml
set -euo pipefail
# shellcheck source=scripts/lib.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
require_tools git tmux yq

[[ $# -eq 0 || "${1:-}" == --write ]] || usage "agent-status.sh [--write]"
now="$(date +%s)"
rows=()
seen=" "

row() {  # window role task status state dirty minutes model
  rows+=("$(printf '%-20s %-9s %-7s %-18s %-8s %-5s %-4s %s' "$@")")
}

task_status() { [[ -f "$(task_file "$1")" ]] && task_get "$1" .status || echo "-"; }

dirty() {
  local wt
  wt="$(worktree_root)/$1"
  [[ -d "$wt" ]] || { echo "-"; return; }
  [[ -n "$(git -C "$wt" status --porcelain)" ]] && echo yes || echo no
}

if session_exists; then
  while IFS=$'\t' read -r _ name role task model dead started; do
    [[ -z "$name" ]] && continue
    state=running
    [[ "$dead" == 1 ]] && state=exited
    mins="-"
    [[ -n "$started" ]] && mins=$(( (now - started) / 60 ))
    if [[ -n "$task" ]]; then
      row "$name" "$role" "$task" "$(task_status "$task")" "$state" "$(dirty "$task")" "$mins" "${model:--}"
      seen+="$task "
    else
      row "$name" "$role" "-" "-" "$state" "-" "$mins" "${model:--}"
    fi
  done < <(list_windows)
else
  echo "session $AGENT_SESSION is not running"
fi

while IFS=$'\t' read -r task agent; do
  [[ -z "$task" || "$seen" == *" $task "* ]] && continue
  row "-" "$agent" "$task" "$(task_status "$task")" "nowindow" "$(dirty "$task")" "-" "-"
done < <(yq -r '.locks[] | .task + "\t" + .agent' "$(locks_file)")

printf '%-20s %-9s %-7s %-18s %-8s %-5s %-4s %s\n' WINDOW ROLE TASK STATUS STATE DIRTY MIN MODEL
if [[ ${#rows[@]} -gt 0 ]]; then printf '%s\n' "${rows[@]}"; fi
echo "live Claude sessions: $(claude_count)/$AGENT_MAX_CLAUDE"

if [[ "${1:-}" == --write ]]; then
  out="$(state_dir)/project-state.yaml"
  {
    echo "# Generated by scripts/agent-status.sh --write. Do not edit."
    echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "session_running: $(session_exists && echo true || echo false)"
    echo "live_claude_sessions: $(claude_count)"
    echo "max_claude_sessions: $AGENT_MAX_CLAUDE"
    echo "agents:"
    list_windows | while IFS=$'\t' read -r _ name role task model dead _; do
      echo "  - {window: \"$name\", role: \"$role\", task: \"$task\", model: \"$model\", exited: $([[ "$dead" == 1 ]] && echo true || echo false)}"
    done
  } > "$out"
  echo "wrote $out"
fi
